/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostelfood;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class change_password extends javax.swing.JFrame {

    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public change_password() {
        initComponents();
        conn = databaseConnection.connection();
        inobox.setText(edit_student.searchid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inobox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cpwbox = new javax.swing.JPasswordField();
        npwbox = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rnpwbox = new javax.swing.JPasswordField();
        changebtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Current Password:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        inobox.setEditable(false);
        inobox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(inobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 280, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Index No:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        cpwbox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(cpwbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 270, 50));

        npwbox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(npwbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 270, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Re Enter Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        rnpwbox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(rnpwbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 270, 50));

        changebtn.setBackground(new java.awt.Color(0, 102, 0));
        changebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        changebtn.setForeground(new java.awt.Color(255, 255, 255));
        changebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-check-icon.png"))); // NOI18N
        changebtn.setText("Change Password");
        changebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebtnActionPerformed(evt);
            }
        });
        jPanel1.add(changebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 220, 50));

        exitbtn.setBackground(new java.awt.Color(102, 0, 0));
        exitbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel1.png"))); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitbtnActionPerformed

    private void changebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebtnActionPerformed
        // TODO add your handling code here:
        String old_pw=cpwbox.getText();
        String new_pw=npwbox.getText();
        String renew_pw=rnpwbox.getText();
        String empty="";
        
        try {
            stmt=conn.createStatement();
            String sql="SELECT password FROM student WHERE index_no='"+edit_student.searchid+"' ";
            rs =stmt.executeQuery(sql);
            if(rs.next()){
                String correct_pw=rs.getString(1);
                //JOptionPane.showMessageDialog(null, correct_pw);
                if(old_pw.equals(correct_pw)){
                    if(new_pw.equals(renew_pw) & !renew_pw.equals(empty) ){
                        
                        stmt=conn.createStatement();
                        String sqlchange="UPDATE student SET password='"+renew_pw+"' WHERE index_no='"+edit_student.searchid+"';";
                        stmt.executeUpdate(sqlchange);
                        JOptionPane.showMessageDialog(null, "Data is successfully Updated");
                        cpwbox.setText("");
                        npwbox.setText("");
                        rnpwbox.setText("");
                    }else{
                        JOptionPane.showMessageDialog(null, "Your New Password and Re Enter Password is no equal!!!");
                        npwbox.setText("");
                        rnpwbox.setText("");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Please Enter Your Correct Old Password!!!");
                    cpwbox.setText("");
                    npwbox.setText("");
                    rnpwbox.setText("");
                }
           }else{
                JOptionPane.showMessageDialog(null, "Error");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_changebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new change_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changebtn;
    private javax.swing.JPasswordField cpwbox;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField inobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField npwbox;
    private javax.swing.JPasswordField rnpwbox;
    // End of variables declaration//GEN-END:variables
}
