/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostelfood;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS
 */
public class collect_food extends javax.swing.JFrame {

    /**
     * Creates new form collect_food
     */
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    int selected_button=0;
    String selected_time="";
    public collect_food() {
        initComponents();
        conn = databaseConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bbtn = new javax.swing.JButton();
        lbtn = new javax.swing.JButton();
        dbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stable = new javax.swing.JTable();
        notcollect = new javax.swing.JButton();
        collect = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jXDatePicker1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        bbtn.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        bbtn.setText("Breakfast");
        bbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbtnActionPerformed(evt);
            }
        });
        jPanel1.add(bbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 140, 40));

        lbtn.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lbtn.setText("Lunch");
        lbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbtnActionPerformed(evt);
            }
        });
        jPanel1.add(lbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 140, 40));

        dbtn.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        dbtn.setText("Dinner");
        dbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbtnActionPerformed(evt);
            }
        });
        jPanel1.add(dbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 140, 40));

        stable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(stable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 550, 600));

        notcollect.setBackground(new java.awt.Color(204, 0, 0));
        notcollect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel1.png"))); // NOI18N
        notcollect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notcollectActionPerformed(evt);
            }
        });
        jPanel1.add(notcollect, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 70, 60));

        collect.setBackground(new java.awt.Color(0, 153, 0));
        collect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-check-icon.png"))); // NOI18N
        collect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectActionPerformed(evt);
            }
        });
        jPanel1.add(collect, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 70, 60));

        jButton1.setBackground(new java.awt.Color(102, 51, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 680, 110, 50));
        jPanel1.add(jXDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker1ActionPerformed
        // TODO add your handling code here:
        dbtn.setBackground(Color.white);
        lbtn.setBackground(Color.white);
        bbtn.setBackground(Color.white);

        DefaultTableModel dm = (DefaultTableModel) stable.getModel();
        dm.getDataVector().removeAllElements();
    }//GEN-LAST:event_jXDatePicker1ActionPerformed

    private void bbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbtnActionPerformed
        // TODO add your handling code here:
        selected_button=1;
        bbtn.setBackground(Color.yellow);
        lbtn.setBackground(Color.white);
        dbtn.setBackground(Color.white);

        Date oDate = jXDatePicker1.getDate();
        DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String select_date = oDateFormat.format(oDate);

        try {
            stmt = conn.createStatement();
            String sql = "SELECT bed_no,date,buy_time,name,type,variation,size,collect FROM student_food WHERE time='Breakfast' AND date='" + select_date + "' ";
            ResultSet res1 = stmt.executeQuery(sql);
            stable.setModel(DbUtils.resultSetToTableModel(res1));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_bbtnActionPerformed

    private void lbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbtnActionPerformed
        // TODO add your handling code here:
        selected_button=2;
        lbtn.setBackground(Color.yellow);
        bbtn.setBackground(Color.white);
        dbtn.setBackground(Color.white);

        Date oDate = jXDatePicker1.getDate();
        DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String select_date = oDateFormat.format(oDate);

        try {
            stmt = conn.createStatement();
            String sql = "SELECT bed_no,date,buy_time,name,type,variation,size,collect FROM student_food WHERE time='Lunch' AND date='" + select_date + "' ";
            ResultSet res1 = stmt.executeQuery(sql);
            stable.setModel(DbUtils.resultSetToTableModel(res1));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_lbtnActionPerformed

    private void dbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbtnActionPerformed
        // TODO add your handling code here:
        selected_button=3;
        dbtn.setBackground(Color.yellow);
        lbtn.setBackground(Color.white);
        bbtn.setBackground(Color.white);

        Date oDate = jXDatePicker1.getDate();
        DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String select_date = oDateFormat.format(oDate);

        try {
            stmt = conn.createStatement();
            String sql = "SELECT bed_no,date,buy_time,name,type,variation,size,collect FROM student_food WHERE time='Dinner' AND date='" + select_date + "' ";
            ResultSet res1 = stmt.executeQuery(sql);
            stable.setModel(DbUtils.resultSetToTableModel(res1));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        
    }//GEN-LAST:event_dbtnActionPerformed

    private void collectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectActionPerformed
        // TODO add your handling code here:
        int column0 = 0;
        int column1 = 1;
        int column2 = 2;
        int row = stable.getSelectedRow();

        String value1 = stable.getModel().getValueAt(row, column0).toString();
        String value2 = stable.getModel().getValueAt(row, column1).toString();
        String value3 = stable.getModel().getValueAt(row, column2).toString();
        try {
            stmt = conn.createStatement();

            String sql = "UPDATE student_food SET collect=1 WHERE bed_no='" + value1 + "' AND date='"+value2+"' AND buy_time='"+value3+"'   ;";

            stmt.executeUpdate(sql);
            
            //displayTable();
            //JOptionPane.showMessageDialog(null, "Data is successfully Updated");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        Date oDate = jXDatePicker1.getDate();
        DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String select_date = oDateFormat.format(oDate);

        try {
            stmt = conn.createStatement();
            
            if(selected_button==1){
                selected_time="Breakfast";
            }else if(selected_button==2){
                selected_time="Lunch";
            }else if(selected_button==3){
                selected_time="Dinner";
            }
            String sql1 = "SELECT bed_no,date,buy_time,name,type,variation,size,collect FROM student_food WHERE time='"+selected_time+"' AND date='" + select_date + "' ";
            ResultSet res1 = stmt.executeQuery(sql1);
            stable.setModel(DbUtils.resultSetToTableModel(res1));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_collectActionPerformed

    private void notcollectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notcollectActionPerformed
        // TODO add your handling code here:
        int column0 = 0;
        int column1 = 1;
        int column2 = 2;
        int row = stable.getSelectedRow();

        String value1 = stable.getModel().getValueAt(row, column0).toString();
        String value2 = stable.getModel().getValueAt(row, column1).toString();
        String value3 = stable.getModel().getValueAt(row, column2).toString();
        try {
            stmt = conn.createStatement();

            String sql = "UPDATE student_food SET collect=0 WHERE bed_no='" + value1 + "' AND date='"+value2+"' AND buy_time='"+value3+"'   ;";

            stmt.executeUpdate(sql);
            //displayTable();
            //JOptionPane.showMessageDialog(null, "Data is successfully Updated");
            try {
            stmt = conn.createStatement();
            Date oDate = jXDatePicker1.getDate();
            DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String select_date = oDateFormat.format(oDate);
            
            if(selected_button==1){
                selected_time="Breakfast";
            }else if(selected_button==2){
                selected_time="Lunch";
            }else if(selected_button==3){
                selected_time="Dinner";
            }
            String sql1 = "SELECT bed_no,date,buy_time,name,type,variation,size,collect FROM student_food WHERE time='"+selected_time+"' AND date='" + select_date + "' ";
            ResultSet res1 = stmt.executeQuery(sql1);
            stable.setModel(DbUtils.resultSetToTableModel(res1));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_notcollectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        student s=new student();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(collect_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(collect_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(collect_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(collect_food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new collect_food().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbtn;
    private javax.swing.JButton collect;
    private javax.swing.JButton dbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jXDatePicker1;
    private javax.swing.JButton lbtn;
    private javax.swing.JButton notcollect;
    private javax.swing.JTable stable;
    // End of variables declaration//GEN-END:variables
}
