/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostelfood;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class edit_login extends javax.swing.JFrame {

    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public edit_login() {
        initComponents();
        conn = databaseConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        npbox = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        rnpbox = new javax.swing.JPasswordField();
        changebtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cpbox = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        nubox = new javax.swing.JTextField();
        cubox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New UserName:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        npbox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(npbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 270, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Re Enter Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        rnpbox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(rnpbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 270, 50));

        changebtn.setBackground(new java.awt.Color(0, 102, 0));
        changebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        changebtn.setForeground(new java.awt.Color(255, 255, 255));
        changebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save-icon.png"))); // NOI18N
        changebtn.setText("Change ");
        changebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebtnActionPerformed(evt);
            }
        });
        jPanel1.add(changebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 220, 50));

        exitbtn.setBackground(new java.awt.Color(102, 0, 0));
        exitbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel1.png"))); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 120, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current UserName:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Current Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        cpbox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(cpbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 270, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 102));
        jLabel6.setText("Edit Admin UserName and Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        nubox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(nubox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 270, 50));

        cubox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(cubox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 270, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebtnActionPerformed
        // TODO add your handling code here:
        String old_user=cubox.getText();
        String old_pw=cpbox.getText();
        String new_user=nubox.getText();
        String new_pw=npbox.getText();
        String renew_pw=rnpbox.getText();
        String empty="";

        try {
            stmt=conn.createStatement();
            //String sql="SELECT * FROM admin WHERE username='"+old_user+"' AND password='"+old_pw+"'";
            String sql="SELECT * FROM admin";
            rs =stmt.executeQuery(sql);
            rs.next();
            //if(rs.next()){
                String correct_user=rs.getString(1);
                String correct_pw=rs.getString(2);
                //JOptionPane.showMessageDialog(null, correct_pw);
                if(old_pw.equals(correct_pw) & old_user.equals(correct_user) ){
                    if(new_pw.equals(renew_pw) & !renew_pw.equals(empty)  ){

                        stmt=conn.createStatement();
                        String sqlchange="UPDATE admin SET username='"+new_user+"' , password='"+renew_pw+"' WHERE username='"+old_user+"';";
                        stmt.executeUpdate(sqlchange);
                        JOptionPane.showMessageDialog(null, "Data is successfully Updated");
                        cubox.setText("");
                        cpbox.setText("");  
                        nubox.setText("");
                        npbox.setText("");
                        rnpbox.setText("");
                    }else{
                        JOptionPane.showMessageDialog(null, "Your New Password and Re Enter Password is no equal!!!");
                        npbox.setText("");
                        rnpbox.setText("");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Please Enter Your Correct Current User Name and Password!!!");
                    cubox.setText("");
                    cpbox.setText("");  
                    nubox.setText("");
                    npbox.setText("");
                    rnpbox.setText("");
                }
            //}else{
                //JOptionPane.showMessageDialog(null, "Error");

           // }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_changebtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        login l=new login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changebtn;
    private javax.swing.JPasswordField cpbox;
    private javax.swing.JTextField cubox;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField npbox;
    private javax.swing.JTextField nubox;
    private javax.swing.JPasswordField rnpbox;
    // End of variables declaration//GEN-END:variables
}
