/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostelfood;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS
 */
public class Menu_Editor extends javax.swing.JFrame {

    Connection conn=null;
    Statement stmt=null;
    ResultSet rs=null;
    
    public Menu_Editor() {
        initComponents();
        conn=databaseConnection.connection();
        displayTable();
    }
    public void displayTable(){
        try {
            stmt=conn.createStatement();
            String sqlone="SELECT * FROM foods WHERE time='Breakfast' ";
            ResultSet resone =stmt.executeQuery(sqlone);
            Btable.setModel(DbUtils.resultSetToTableModel(resone));
            
            String sqltwo="SELECT * FROM foods WHERE time='Lunch' ";
            ResultSet restwo =stmt.executeQuery(sqltwo);
            Ltable.setModel(DbUtils.resultSetToTableModel(restwo));
            
            String sqlthree="SELECT * FROM foods WHERE time='Dinner' ";
            ResultSet resthree =stmt.executeQuery(sqlthree);
            Dtable.setModel(DbUtils.resultSetToTableModel(resthree));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }
    public void changeColor(){
        //model.setRowColour(1, Color.YELLOW);
        /*stmt=conn.createStatement();
        String sqlone="SELECT * FROM foods WHERE time='Breakfast' ";
        ResultSet resone =stmt.executeQuery(sqlone);
        Btable.setModel(DbUtils.resultSetToTableModel(resone));*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Dtable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Btable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Ltable = new javax.swing.JTable();
        Bopen = new javax.swing.JButton();
        Bclose = new javax.swing.JButton();
        Lclose = new javax.swing.JButton();
        Lopen = new javax.swing.JButton();
        Dclose = new javax.swing.JButton();
        Dopen = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Editor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        Dtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Dtable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 560, 220));

        Btable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Btable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 560, 210));

        Ltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Ltable);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 560, 230));

        Bopen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel1.png"))); // NOI18N
        Bopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BopenActionPerformed(evt);
            }
        });
        jPanel1.add(Bopen, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 80, 60));

        Bclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-check-icon.png"))); // NOI18N
        Bclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcloseActionPerformed(evt);
            }
        });
        jPanel1.add(Bclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 80, 60));

        Lclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-check-icon.png"))); // NOI18N
        Lclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LcloseActionPerformed(evt);
            }
        });
        jPanel1.add(Lclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 80, 60));

        Lopen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel1.png"))); // NOI18N
        Lopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LopenActionPerformed(evt);
            }
        });
        jPanel1.add(Lopen, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 80, 60));

        Dclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-check-icon.png"))); // NOI18N
        Dclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DcloseActionPerformed(evt);
            }
        });
        jPanel1.add(Dclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, 80, 60));

        Dopen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel1.png"))); // NOI18N
        Dopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DopenActionPerformed(evt);
            }
        });
        jPanel1.add(Dopen, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, 80, 60));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel1.png"))); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 700, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcloseActionPerformed
        // TODO add your handling code here:
        int column = 0;
        int row = Btable.getSelectedRow();
        String value = Btable.getModel().getValueAt(row, column).toString();
        try {
            stmt=conn.createStatement();

            String sql="UPDATE foods SET open=0 WHERE food_id='"+value+"';";

            stmt.executeUpdate(sql);
            displayTable();
            //JOptionPane.showMessageDialog(null, "Data is successfully Updated");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_BcloseActionPerformed

    private void BopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BopenActionPerformed
        // TODO add your handling code here:
        int column = 0;
        int row = Btable.getSelectedRow();
        String value = Btable.getModel().getValueAt(row, column).toString();
        try {
            stmt=conn.createStatement();

            String sql="UPDATE foods SET open=1 WHERE food_id='"+value+"';";

            stmt.executeUpdate(sql);
            displayTable();
            //JOptionPane.showMessageDialog(null, "Data is successfully Updated");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BopenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        admin a=new admin();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LcloseActionPerformed
        // TODO add your handling code here:
         int column = 0;
        int row = Ltable.getSelectedRow();
        String value = Ltable.getModel().getValueAt(row, column).toString();
        try {
            stmt=conn.createStatement();

            String sql="UPDATE foods SET open=0 WHERE food_id='"+value+"';";

            stmt.executeUpdate(sql);
            displayTable();
            //JOptionPane.showMessageDialog(null, "Data is successfully Updated");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_LcloseActionPerformed

    private void LopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LopenActionPerformed
        // TODO add your handling code here:
        int column = 0;
        int row = Ltable.getSelectedRow();
        String value = Ltable.getModel().getValueAt(row, column).toString();
        try {
            stmt=conn.createStatement();

            String sql="UPDATE foods SET open=1 WHERE food_id='"+value+"';";

            stmt.executeUpdate(sql);
            displayTable();
            //JOptionPane.showMessageDialog(null, "Data is successfully Updated");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_LopenActionPerformed

    private void DcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DcloseActionPerformed
        // TODO add your handling code here:
        int column = 0;
        int row = Dtable.getSelectedRow();
        String value = Dtable.getModel().getValueAt(row, column).toString();
        try {
            stmt=conn.createStatement();

            String sql="UPDATE foods SET open=0 WHERE food_id='"+value+"';";

            stmt.executeUpdate(sql);
            displayTable();
            //JOptionPane.showMessageDialog(null, "Data is successfully Updated");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DcloseActionPerformed

    private void DopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DopenActionPerformed
        // TODO add your handling code here:
        int column = 0;
        int row = Dtable.getSelectedRow();
        String value = Dtable.getModel().getValueAt(row, column).toString();
        try {
            stmt=conn.createStatement();

            String sql="UPDATE foods SET open=1 WHERE food_id='"+value+"';";

            stmt.executeUpdate(sql);
            displayTable();
            //JOptionPane.showMessageDialog(null, "Data is successfully Updated");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DopenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bclose;
    private javax.swing.JButton Bopen;
    private javax.swing.JTable Btable;
    private javax.swing.JButton Dclose;
    private javax.swing.JButton Dopen;
    private javax.swing.JTable Dtable;
    private javax.swing.JButton Lclose;
    private javax.swing.JButton Lopen;
    private javax.swing.JTable Ltable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
