/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hostelfood;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.text.DateFormat;  
import java.text.SimpleDateFormat;  
import java.util.Date;  
import java.util.Calendar; 
import javax.swing.table.DefaultTableModel;

public class order extends javax.swing.JFrame {

    Connection conn=null;
    Statement stmt=null;
    ResultSet rs=null;
    
    float balance=0;
    
    public order() {
        initComponents();
        conn=databaseConnection.connection();
        Date date = Calendar.getInstance().getTime();  
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
        DateFormat timeformat = new SimpleDateFormat("hh:mm:ss"); 
        String strDate = dateFormat.format(date);  
        String strtime = timeformat.format(date);  
        datebox.setText(strDate);
        displayTable();
    }
    public void displayTable(){
        try {
            stmt=conn.createStatement();
            String sqlone="SELECT food_id,time,type,variation,size,price FROM foods WHERE time='Breakfast' AND open=1 ";
            ResultSet resone =stmt.executeQuery(sqlone);
            breakfastT.setModel(DbUtils.resultSetToTableModel(resone));
            
            String sqltwo="SELECT food_id,time,type,variation,size,price FROM foods WHERE time='Lunch' AND open=1 ";
            ResultSet restwo =stmt.executeQuery(sqltwo);
            lunchT.setModel(DbUtils.resultSetToTableModel(restwo));
            
            String sqlthree="SELECT food_id,time,type,variation,size,price FROM foods WHERE time='Dinner' AND open=1 ";
            ResultSet resthree =stmt.executeQuery(sqlthree);
            dinnerT.setModel(DbUtils.resultSetToTableModel(resthree));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void displayBuyTable(){
        try {
            Date date = Calendar.getInstance().getTime();  
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
            DateFormat timeformat = new SimpleDateFormat("hh:mm:ss"); 
            String strDate = dateFormat.format(date);  
            String strtime = timeformat.format(date);  

            String bed_no=bnobox.getText();
            String name=namebox.getText();
            String index_no=inobox.getText();
            String get_time=(String) timebox.getSelectedItem();
            String get_type=(String) typebox.getSelectedItem();
            String get_var=(String) variationbox.getSelectedItem();
            String get_size=(String) sizebox.getSelectedItem();
            String get_price=pricebox.getText();
            
            Object[] row={bed_no,name,strDate,get_time,get_type,get_var,get_size,get_price};
            DefaultTableModel model=(DefaultTableModel) buytable.getModel();
            model.addRow(row);
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bnobox = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inobox = new javax.swing.JTextField();
        namebox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        datebox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        buytable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        totalbox = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        buybtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        mytotalbox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        breakfastT = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lunchT = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        dinnerT = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        timebox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        typebox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        variationbox = new javax.swing.JComboBox<>();
        sizebox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        enter = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        pricebox = new javax.swing.JTextField();
        addcart = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bed No:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 31, -1, 24));

        bnobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnoboxActionPerformed(evt);
            }
        });
        jPanel1.add(bnobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 30, 100, 33));

        searchbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 32, 99, 33));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 76, 68, 44));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Index No:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 126, 102, 49));

        inobox.setEditable(false);
        inobox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inoboxActionPerformed(evt);
            }
        });
        jPanel1.add(inobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 136, 270, 35));

        namebox.setEditable(false);
        namebox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameboxActionPerformed(evt);
            }
        });
        jPanel1.add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 84, 270, 35));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 195, 61, -1));

        datebox.setEditable(false);
        datebox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        datebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateboxActionPerformed(evt);
            }
        });
        jPanel1.add(datebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 193, 270, 35));

        buytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bed No", "Name", "Date", "Time", "Type", "Variation", "Size", "Price"
            }
        ));
        jScrollPane1.setViewportView(buytable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 240, 407, 238));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));

        totalbox.setEditable(false);
        totalbox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalboxActionPerformed(evt);
            }
        });
        jPanel1.add(totalbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 490, 271, 35));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("My Balance");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 646, 137, 38));

        buybtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buybtn.setText("Buy");
        buybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buybtnActionPerformed(evt);
            }
        });
        jPanel1.add(buybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 592, 113, 36));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("Cancel");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 592, 113, 36));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Your Price:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 541, -1, -1));

        mytotalbox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mytotalbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mytotalboxActionPerformed(evt);
            }
        });
        jPanel1.add(mytotalbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 539, 271, 35));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Today Menu");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 6, 142, -1));

        breakfastT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(breakfastT);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1013, 98, 366, 136));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Breakfast");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1105, 55, 110, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lunch");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1105, 246, 98, -1));

        lunchT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(lunchT);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1013, 299, 366, 168));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dinner");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1116, 503, 104, -1));

        dinnerT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(dinnerT);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1013, 540, 366, 164));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Time:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 34, -1, 24));

        timebox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        timebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a time", "Breakfast", "Lunch", "Dinner" }));
        timebox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                timeboxItemStateChanged(evt);
            }
        });
        timebox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeboxMouseClicked(evt);
            }
        });
        timebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeboxActionPerformed(evt);
            }
        });
        jPanel1.add(timebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 27, 206, 38));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Type:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 100, -1, 24));

        typebox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        typebox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeboxItemStateChanged(evt);
            }
        });
        typebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeboxActionPerformed(evt);
            }
        });
        jPanel1.add(typebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 93, 206, 38));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Variation:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 172, -1, 24));

        variationbox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        variationbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                variationboxItemStateChanged(evt);
            }
        });
        variationbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variationboxActionPerformed(evt);
            }
        });
        jPanel1.add(variationbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 165, 206, 38));

        sizebox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(sizebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 240, 206, 38));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Size:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 247, -1, 24));

        enter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        jPanel1.add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 318, 109, 38));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Price:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 402, -1, -1));

        pricebox.setEditable(false);
        pricebox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pricebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceboxActionPerformed(evt);
            }
        });
        jPanel1.add(pricebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 393, 235, 48));

        addcart.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addcart.setText("Add To Cart");
        addcart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcartActionPerformed(evt);
            }
        });
        jPanel1.add(addcart, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 496, -1, 38));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setText("Cancel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 496, 109, 38));

        jButton8.setBackground(new java.awt.Color(255, 0, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel1.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, 120, 60));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Exit");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 660, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1453, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnoboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnoboxActionPerformed

    private void inoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inoboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inoboxActionPerformed

    private void nameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameboxActionPerformed

    private void dateboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateboxActionPerformed

    private void totalboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalboxActionPerformed

    private void mytotalboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mytotalboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mytotalboxActionPerformed

    private void priceboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceboxActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        try {
            String searchntn=bnobox.getText();
            
            String sql="SELECT * FROM student WHERE bed_no='"+searchntn+"'";
            stmt=conn.createStatement();
            rs=stmt.executeQuery(sql);
            if(rs.next()){
                namebox.setText(rs.getString(3));
                inobox.setText(rs.getString(1));
                rs.close();
                stmt.close();
           }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
       
    }//GEN-LAST:event_searchbtnActionPerformed

    private void timeboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeboxMouseClicked
        // Error
        /*try {
            String get_time=(String) timebox.getSelectedItem();
            String sql="SELECT type FROM foods WHERE time='"+get_time+"' AND open=1 ";
            stmt=conn.createStatement();
            rs=stmt.executeQuery(sql);
            typebox.removeAllItems();
            int i=0;
            while(rs.next()){
                typebox.addItem(rs.getString("type"));
               
            }
            rs.close();
            stmt.close();
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }*/
        
        
    }//GEN-LAST:event_timeboxMouseClicked

    private void timeboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_timeboxItemStateChanged
        // Error
       
       /*if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
       
            
            try {
                String get_time=(String) timebox.getSelectedItem();
                JOptionPane.showMessageDialog(null, get_time);
                String sql="SELECT type FROM foods WHERE time='"+get_time+"' AND open=1 ";
                stmt=conn.createStatement();
                rs=stmt.executeQuery(sql);
                typebox.removeAllItems();
                int i=0;
                while(rs.next()){
                    JOptionPane.showMessageDialog(null,rs.getString("type"));
                    typebox.addItem(rs.getString("type"));
                    
                }
                rs.close();
                stmt.close();
                
            
            }catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
           //JOptionPane.showMessageDialog(null, evt.getItem());
        }
       //JOptionPane.showMessageDialog(null, evt.getItem()+" "+evt.getStateChange());*/
       
    }//GEN-LAST:event_timeboxItemStateChanged

    private void variationboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_variationboxItemStateChanged
        // Error
        /*try {
            String get_time=(String) timebox.getSelectedItem();
            String get_type=(String) typebox.getSelectedItem();
            String get_variation=(String) variationbox.getSelectedItem();
            String sql="SELECT size FROM foods WHERE time='"+get_time+"' AND type='"+get_type+"' AND variation='"+get_variation+"' AND open=1 ";
            stmt=conn.createStatement();
            rs=stmt.executeQuery(sql);
            sizebox.removeAllItems();
            while(rs.next()){
                sizebox.addItem(rs.getString("size"));
               
            }
            //rs.close();
            //stmt.close();
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }*/
    }//GEN-LAST:event_variationboxItemStateChanged

    private void typeboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeboxItemStateChanged
        // Error
        /*if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            try {
               String get_time=(String) timebox.getSelectedItem();
               String get_type=(String) typebox.getSelectedItem();
               String sql="SELECT variation FROM foods WHERE time='"+get_time+"' AND type='"+get_type+"' AND open=1 ";
               stmt=conn.createStatement();
               rs=stmt.executeQuery(sql);
               variationbox.removeAllItems();
               while(rs.next()){
                   variationbox.addItem(rs.getString("variation"));

               }
               //rs.close();
               //stmt.close();

           }catch (Exception e) {
               JOptionPane.showMessageDialog(null, e);
           }
        }*/
           
    }//GEN-LAST:event_typeboxItemStateChanged

    private void timeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeboxActionPerformed
        // TODO add your handling code here:
        Statement stmt_time=null;
        ResultSet rs_time=null;
        typebox.removeAllItems(); 
        variationbox.removeAllItems();
        sizebox.removeAllItems();
         try {
            String get_time=(String) timebox.getSelectedItem();
            String sql="SELECT type FROM foods WHERE time='"+get_time+"' AND open=1 ";
            stmt_time=conn.createStatement();
            rs_time=stmt_time.executeQuery(sql);
            typebox.removeAllItems();
            while(rs_time.next()){
                typebox.addItem(rs_time.getString("type"));
               
            }
            rs_time.close();
            stmt_time.close();
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_timeboxActionPerformed

    private void typeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeboxActionPerformed
        // TODO add your handling code here:
        Statement stmt_type=null;
        ResultSet rs_type=null;
        variationbox.removeAllItems();
        sizebox.removeAllItems();
        try {
            String get_time=(String) timebox.getSelectedItem();
            String get_type=(String) typebox.getSelectedItem();
            String sql="SELECT variation FROM foods WHERE time='"+get_time+"' AND type='"+get_type+"' AND open=1 ";
            stmt_type=conn.createStatement();
            rs_type=stmt_type.executeQuery(sql);
            variationbox.removeAllItems();
            while(rs_type.next()){
                variationbox.addItem(rs_type.getString("variation"));
               
            }
            rs_type.close();
            stmt_type.close();
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_typeboxActionPerformed

    private void variationboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variationboxActionPerformed
        // TODO add your handling code here:
        Statement stmt_var=null;
        ResultSet rs_var=null;
        sizebox.removeAllItems();
        try {
            String get_time=(String) timebox.getSelectedItem();
            String get_type=(String) typebox.getSelectedItem();
            String get_var=(String) variationbox.getSelectedItem();
            
            String sql="SELECT size FROM foods WHERE time='"+get_time+"' AND type='"+get_type+"' AND variation='"+get_var+"' AND open=1 ";
            stmt_var=conn.createStatement();
            rs_var=stmt_var.executeQuery(sql);
            sizebox.removeAllItems();
            while(rs_var.next()){
                sizebox.addItem(rs_var.getString("size"));
               
            }
            rs_var.close();
            stmt_var.close();
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_variationboxActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
        Statement stmt_enter=null;
        ResultSet rs_enter=null;
        try {
            String get_time=(String) timebox.getSelectedItem();
            String get_type=(String) typebox.getSelectedItem();
            String get_var=(String) variationbox.getSelectedItem();
            String get_size=(String) sizebox.getSelectedItem();
            
            String sql="SELECT price FROM foods WHERE time='"+get_time+"' AND type='"+get_type+"' AND variation='"+get_var+"' AND size='"+get_size+"' AND open=1 ";
            stmt_enter=conn.createStatement();
            rs_enter=stmt_enter.executeQuery(sql);
            if(rs_enter.next()){
                pricebox.setText(rs_enter.getString("price"));
               
            }
            rs_enter.close();
            stmt_enter.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_enterActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        pricebox.setText("");
        typebox.removeAllItems(); 
        variationbox.removeAllItems();
        sizebox.removeAllItems();
        timebox.setSelectedIndex(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void addcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcartActionPerformed
        // TODO add your handling code here:
        Date date = Calendar.getInstance().getTime();  
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
        DateFormat timeformat = new SimpleDateFormat("hh:mm:ss"); 
        String strDate = dateFormat.format(date);  
        String strtime = timeformat.format(date);  
        
        String bed_no=bnobox.getText();
        String name=namebox.getText();
        String index_no=inobox.getText();
        String get_time=(String) timebox.getSelectedItem();
        String get_type=(String) typebox.getSelectedItem();
        String get_var=(String) variationbox.getSelectedItem();
        String get_size=(String) sizebox.getSelectedItem();
        String get_price=pricebox.getText();
        
        if(index_no.equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter your bed no!!");
        }else{
            try {
                stmt=conn.createStatement();
                String sql="INSERT INTO student_food VALUES('"+bed_no+"','"+name+"','"+index_no+"','"+dateFormat.format(date)+"','"+timeformat.format(date)+"','"+get_time+"','"+get_type+"','"+get_var+"','"+get_size+"','"+get_price+"','0')";
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data is successfully Inserted");
                displayBuyTable();
                float temp_price=Float.parseFloat(get_price);
                balance=balance+temp_price;
                totalbox.setText(Float.toString(balance));
                //bnobox.setText("");
                //namebox.setText("");
                //inobox.setText("");
                pricebox.setText("");
                typebox.removeAllItems(); 
                variationbox.removeAllItems();
                sizebox.removeAllItems();
                timebox.setSelectedIndex(0);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_addcartActionPerformed

    private void buybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buybtnActionPerformed
        // TODO add your handling code here:
        Float my_price=Float.parseFloat(mytotalbox.getText());
        Float my_balance=my_price-balance;
        float old_balance=0;
        float full_balance=0;
        String bed_no=bnobox.getText();
        try {
            Statement stmt_get=null;
            ResultSet rs_get=null;
            stmt_get=conn.createStatement();
            String sql_get="SELECT balance FROM student WHERE bed_no='"+bed_no+"' ";
            rs_get=stmt_get.executeQuery(sql_get);
            if(rs_get.next()){
                old_balance=Float.parseFloat(rs_get.getString("balance"));
               
            }
            rs_get.close();
            stmt_get.close();
            full_balance=old_balance+my_balance;
            String sql="UPDATE student SET balance='"+full_balance+"' WHERE bed_no='"+bed_no+"' ";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Thank You");
            bnobox.setText("");
            namebox.setText("");
            inobox.setText("");
            totalbox.setText("");
            mytotalbox.setText("");
            
            DefaultTableModel dm = (DefaultTableModel)buytable.getModel();
            dm.getDataVector().removeAllElements();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_buybtnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        student s=new student();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed
       
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcart;
    private javax.swing.JTextField bnobox;
    private javax.swing.JTable breakfastT;
    private javax.swing.JButton buybtn;
    private javax.swing.JTable buytable;
    private javax.swing.JTextField datebox;
    private javax.swing.JTable dinnerT;
    private javax.swing.JButton enter;
    private javax.swing.JTextField inobox;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable lunchT;
    private javax.swing.JTextField mytotalbox;
    private javax.swing.JTextField namebox;
    private javax.swing.JTextField pricebox;
    private javax.swing.JButton searchbtn;
    private javax.swing.JComboBox<String> sizebox;
    private javax.swing.JComboBox<String> timebox;
    private javax.swing.JTextField totalbox;
    private javax.swing.JComboBox<String> typebox;
    private javax.swing.JComboBox<String> variationbox;
    // End of variables declaration//GEN-END:variables
}
